-- CONTROL DE VISITAS - SUPABASE
-- Ejecutar este archivo en Supabase -> SQL Editor.
-- IMPORTANTE: crear el primer administrador con la Edge Function
-- admin-bootstrap incluida en este proyecto, o desde el panel de Supabase.

create extension if not exists pgcrypto;

create table if not exists public.administradores (
  id uuid primary key references auth.users(id) on delete cascade,
  usuario text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.visitas (
  id bigint generated by default as identity primary key,
  dni text not null unique,
  nombre text not null,
  fecha_visita timestamptz not null default now()
);

alter table public.administradores enable row level security;
alter table public.visitas enable row level security;

-- Función interna: determina si el usuario autenticado es administrador.
create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.administradores a
    where a.id = auth.uid()
  );
$$;

revoke all on function public.es_admin() from public;
grant execute on function public.es_admin() to authenticated;

-- Administradores: solo administradores autenticados pueden consultar la tabla.
drop policy if exists "admins_select" on public.administradores;
create policy "admins_select"
on public.administradores for select
to authenticated
using (public.es_admin());

-- Visitas: solo administradores pueden consultar/modificar directamente.
drop policy if exists "visitas_admin_select" on public.visitas;
create policy "visitas_admin_select"
on public.visitas for select
to authenticated
using (public.es_admin());

drop policy if exists "visitas_admin_insert" on public.visitas;
create policy "visitas_admin_insert"
on public.visitas for insert
to authenticated
with check (public.es_admin());

drop policy if exists "visitas_admin_update" on public.visitas;
create policy "visitas_admin_update"
on public.visitas for update
to authenticated
using (public.es_admin())
with check (public.es_admin());

drop policy if exists "visitas_admin_delete" on public.visitas;
create policy "visitas_admin_delete"
on public.visitas for delete
to authenticated
using (public.es_admin());

-- Consulta pública de un DNI concreto.
-- No se habilita SELECT público sobre toda la tabla.
create or replace function public.consultar_visita(p_dni text)
returns table (
  id bigint,
  dni text,
  nombre text,
  fecha_visita timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select v.id, v.dni, v.nombre, v.fecha_visita
  from public.visitas v
  where v.dni = trim(p_dni)
  limit 1;
$$;

revoke all on function public.consultar_visita(text) from public;
grant execute on function public.consultar_visita(text) to anon, authenticated;

-- Evita que se pueda insertar una visita desde el navegador sin ser admin.
revoke all on table public.visitas from anon;
revoke all on table public.administradores from anon;

-- Permisos para el rol autenticado; RLS sigue controlando qué filas puede tocar.
grant select, insert, update, delete on public.visitas to authenticated;
grant select on public.administradores to authenticated;

grant usage, select on sequence public.visitas_id_seq to authenticated;

-- Índices.
create unique index if not exists visitas_dni_idx on public.visitas(dni);
create unique index if not exists administradores_usuario_idx on public.administradores(usuario);
